# Generated by Django 5.0.2 on 2024-02-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('SHOES', 'SHOES'), ('SHIRTS', 'SHIRTS'), ('PANTS', 'PANTS'), ('HATS', 'HATS')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount', models.PositiveSmallIntegerField(null=True)),
                ('color', models.CharField(choices=[('RED', 'RD'), ('BLUE', 'BE'), ('WHITE', 'WE'), ('BLACK', 'BK'), ('GREEN', 'GN'), ('ORANGE', 'OE')], max_length=10)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=4)),
            ],
        ),
    ]
